import Vue from 'vue'
import {
  MazAvatar,
  MazBottomSheet,
  MazBtn,
  MazBtnGroup,
  MazCard,
  MazCarousel,
  MazCheckbox,
  MazCollapse,
  MazDialog,
  MazDraggableList,
  MazDropdown,
  MazDropzone,
  MazFlex,
  MazGallery,
  MazImg,
  MazInput,
  MazInputTags,
  MazList,
  MazListItem,
  MazLoader,
  MazPagination,
  MazPicker,
  MazPlotly,
  MazProgressBar,
  MazPhoneNumberInput,
  MazRadio,
  MazReadMore,
  MazResponsiveMenu,
  MazSearch,
  MazSelect,
  MazSlider,
  MazSidebar,
  MazSpinner,
  MazStepper,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand,
} from 'maz-ui'

Vue.use(MazAvatar)
Vue.use(MazBottomSheet)
Vue.use(MazBtn)
Vue.use(MazBtnGroup)
Vue.use(MazCard)
Vue.use(MazCarousel)
Vue.use(MazCheckbox)
Vue.use(MazCollapse)
Vue.use(MazDialog)
Vue.use(MazDraggableList)
Vue.use(MazDropdown)
Vue.use(MazDropzone)
Vue.use(MazFlex)
Vue.use(MazGallery)
Vue.use(MazImg)
Vue.use(MazInput)
Vue.use(MazInputTags)
Vue.use(MazList)
Vue.use(MazListItem)
Vue.use(MazLoader)
Vue.use(MazPagination)
Vue.use(MazPicker)
Vue.use(MazPlotly)
Vue.use(MazProgressBar)
Vue.use(MazPhoneNumberInput)
Vue.use(MazRadio)
Vue.use(MazReadMore)
Vue.use(MazResponsiveMenu)
Vue.use(MazSearch)
Vue.use(MazSelect)
Vue.use(MazSlider)
Vue.use(MazSidebar)
Vue.use(MazSpinner)
Vue.use(MazStepper)
Vue.use(MazSwitch)
Vue.use(MazTabsBar)
Vue.use(MazTabsContent)
Vue.use(MazTabsContentItem)
Vue.use(MazTransitionExpand)
